version: '3.9'

services:
  nginx:
    image: nginx:1.28.1 # Change version
    container_name: nginx_php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.4.17-fpm # Change version
    container_name: php_fpm
    volumes:

      - ./:/var/www/html
